# Generated by Django 2.2.3 on 2019-08-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vokvarinn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='water_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcelery.IntervalSchedule'),
        ),
    ]
