# Generated by Django 2.2.3 on 2019-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vokvarinn', '0002_auto_20190813_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantlog',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
