# Generated by Django 2.2.3 on 2019-08-14 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Vokvarinn', '0003_plantlog_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantlog',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='last_water',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last water'),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Vokvarinn.Plants', verbose_name='Plant name'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/plant_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='info_url',
            field=models.URLField(blank=True, null=True, verbose_name='Info url'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='last_water',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last water'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Plant name'),
        ),
        migrations.AlterField(
            model_name='plants',
            name='water_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcelery.IntervalSchedule', verbose_name='Watering schedule'),
        ),
    ]
